[package]
name = "aoc2021"
version = "0.18.1"
edition = "2021"

[lib]
name = "aocmaxnoe2021"
path = "src/lib.rs"

[dependencies]
reqwest = "0.9.18"
itertools = "0.10.3"
regex = "1"
lazy_static = "1.4.0"
phf = { version = "0.9", features = ["macros"] }
